### ISSUE TITLE
Outing table

### ISSUE THREAD

**Issue by rbalazs** [rbalazs/darts-scoreboard#12]
Lets implement a module, that revecives a number (current score), and return a string (the outing combination)

var plan = OutingTable.doPlan('120'); // "T20 S20 D20"
var plan = OutingTable.doPlan('79'); // "T13 D20"

I could be trivially covered into unit test. Shall be displayed on a popup above score.

**Comment by richercs** [comment]
resolved function, missing unit test and proper gui

**Comment by richercs** [comment]
Duplicated in #16
