### ISSUE TITLE
Double outing UI nonsense

### ISSUE THREAD

**Issue by rbalazs** [rbalazs/darts-scoreboard#16]

**Comment by richercs** [comment]
TODO:
Updgrade the double game button to bootstrap switch.
Only show the checkout string if the score is a possible checkout not a regular number.
Do not show single number when throwing last dart. (example: D10 instead of 20)
Better layout!

**Comment by rbalazs** [comment]
Moving on "Do not show single number when throwing last dart", other point become irrelevant with new logic.
